### PR TITLE
[IMP][14.0] sale_comment_template

### PR DESCRIPTION
**Pull request by AshishHirapara**
Added dynamic placeholders support for sale order comment

### CODE REVIEW

**Review by francesco-ooops — COMMENTED** [review]
functional review ok!

@feketemihai what do you say?

**Review by SicurSam — APPROVED** [review]
functional review ok!

**Review by francesco-ooops — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers good for merge? :)

**Comment by AshishHirapara** [comment]
@pedrobaeza it came to my notice that to add the dynamic placeholder feature in the sale_comment_template module, we need to inherit the base_comment_template module. And it is working fine, but if we do the same approach for the other module to add the dynamic placeholder there, we again need to inherit it. So instead I suggest moving the inheritance to the base module and using that to have placeholders in another module. Let me know if you think the same.

**Comment by pedrobaeza** [comment]
OK, please do the PR with such movement.

**Comment by AshishHirapara** [comment]
@pedrobaeza ok, thanks!

**Comment by francesco-ooops** [comment]
@AshishHirapara please revert this

**Comment by AshishHirapara** [comment]
> @AshishHirapara please revert this

https://github.com/OCA/sale-reporting/pull/184

**Pull request merged**
