### PR TITLE
[14.0][NEW] sale_report_crossed_out_original_price: Price without discount crossed out on sales report

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
NEW module. 
When there is a discount and the discount policy is "Show public price & discount to the customer" this module allows you to generate sales reports crossing out the original price of each sale line and with the price with the discount applied below it.

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten @manuelregidor @luis-ron

**Comment by ValentinVinagre** [comment]
> @ValentinVinagre @HaraldPanten @manuelregidor @luis-ron

Review the pre-commit please

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten @manuelregidor @luis-ron 

Reviewed

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by HaraldPanten** [comment]
Hi @angelgarciadelachica Just a small improvement of the readme...

Could you add that screenshot in order to show the effect of the module, please? see attached:

Example screenshot


Here you can see an example on how to add images in a readme file. Let me know if you have any question. --> https://github.com/OCA/web/pull/2153/files#diff-1ec46879ff2b352ac766576356fb3044472d745e21ed8af1d4abf7142578823e

THX.

**Comment by angelgarciadelachica** [comment]
@HaraldPanten
Done. Anything else? 
Thanks for the suggestion! :-)

**Comment by angelgarciadelachica** [comment]
This PR continue in 
https://github.com/OCA/sale-reporting/pull/137

**Pull request closed without merging**
