### PR TITLE
[MIG] sale_order_line_position: Migration to 16.0

### PR DESCRIPTION
**Pull request by ajaniszewska-dev**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by yankinmax — APPROVED** [review]

**Comment by simahawk** [comment]
@ajaniszewska-dev looks good but please, fix the migration commit msg: it should include the module name.
And you can squash the previous commit on it.

**Comment by simahawk** [comment]
@sbidoul there's no runboat. Is this normal?

**Comment by ajaniszewska-dev** [comment]
> @ajaniszewska-dev looks good but please, fix the migration commit msg: it should include the module name. And you can squash the previous commit on it.

@simahawk  thank you, done.

**Pull request merged**
