### PR TITLE
[13.0][ADD] sale_report_delivered: New module. Sale report from deliveries

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT32439

ping @chienandalu @CarlosRoca13

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Code review. Not tested :+1:

**Comment by pedrobaeza** [comment]
Shouldn't this be included as new measures in the existing sales report?

**Comment by sergio-teruel** [comment]
No

**Comment by pedrobaeza** [comment]
OK:

/ocabot merge nobump

**Pull request merged**
