### PR TITLE
[14.0] [IMP] Improve sale comment template rendering.

### PR DESCRIPTION
**Pull request by feketemihai**
Depends on [OCA/reporting-engine#574](https://github.com/OCA/reporting-engine/pull/574)

### CODE REVIEW

**Comment by elvise** [comment]
@feketemihai can you rebase and fix travis ?

**Comment by elvise** [comment]
Hi @sbidoul can you check runboat please ?

**Comment by sbidoul** [comment]
@elvise it's an old PR. It is likely that the build has been evicted to make room for newer ones. Please rebase to get a fresh build.

**Comment by francesco-ooops** [comment]
@feketemihai could you rebase for testing?

**Comment by francesco-ooops** [comment]
@feketemihai can you rebase this one too?

**Comment by feketemihai** [comment]
> Depends on [OCA/reporting-engine#574](https://github.com/OCA/reporting-engine/pull/574)

@francesco-ooops I can rebase, but will be good to do a rebase after https://github.com/OCA/reporting-engine/pull/574 is merged, like this you can also test it, otherwise no.

**Comment by francesco-ooops** [comment]
> > Depends on [OCA/reporting-engine#574](https://github.com/OCA/reporting-engine/pull/574)
> 
> @francesco-ooops I can rebase, but will be good to do a rebase after [OCA/reporting-engine#574](https://github.com/OCA/reporting-engine/pull/574) is merged, like this you can also test it, otherwise no.

Thanks, so you don't think this module can be tested on runboat until 574 is merged?

**Comment by francesco-ooops** [comment]
> > Depends on [OCA/reporting-engine#574](https://github.com/OCA/reporting-engine/pull/574)
> 
> @francesco-ooops I can rebase, but will be good to do a rebase after [OCA/reporting-engine#574](https://github.com/OCA/reporting-engine/pull/574) is merged, like this you can also test it, otherwise no.

Hi, merged now! @feketemihai can you rebase?

**Comment by elvise** [comment]
@HviorForgeFlow please check this, i think it’s ready for merge.

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by feketemihai** [comment]
@elvise Theer are PR for invoice and picking also in https://github.com/OCA/account-invoice-reporting/pull/211 and https://github.com/OCA/stock-logistics-reporting/pull/177

**Comment by elvise** [comment]
> @elvise Theer are PR for invoice and picking also in https://github.com/OCA/account-invoice-reporting/pull/211 and https://github.com/OCA/stock-logistics-reporting/pull/177
> 
> 

@feketemihai thanks for links 
This afternoon i will check and i will do reviews

**Review by HviorForgeFlow — APPROVED** [review]
Code review

**Comment by elvise** [comment]
@OCA/crm-sales-marketing-maintainers merge ? :)

**Comment by elvise** [comment]
@HviorForgeFlow can we merge ?

**Comment by elvise** [comment]
@feketemihai what do you think can we add Dynamic Placeholder Generator  ? 
(Just for improve the UX)
IMG_1117

**Comment by elvise** [comment]
> @elvise Theer are PR for invoice and picking also in [OCA/account-invoice-reporting#211](https://github.com/OCA/account-invoice-reporting/pull/211) and [OCA/stock-logistics-reporting#177](https://github.com/OCA/stock-logistics-reporting/pull/177)

Done! :) 

From my perspective we need to add the placeholder generator for each one

**Comment by feketemihai** [comment]
Hi,

probably yes, i think it can be added, but this was not my scope, so i
suggest to merge this one like this, and after we can check in separate
PR's.

Regards / Cu respect,
Mihai Fekete

NextERP Romania S.R.L.
600B, Peciu Nou, Romania

E-mail: ***@***.***
Telefon: ‪0788-749989‬
Website: https://nexterp.ro

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers could this be merged?

**Comment by elvise** [comment]
@OCA/crm-sales-marketing-maintainers is there someone for this PR ?

**Comment by francesco-ooops** [comment]
> Hi, probably yes, i think it can be added, but this was not my scope, so i suggest to merge this one like this, and after we can check in separate PR's. 

Hi @feketemihai , do you think you'll have some time to add this feature?

**Comment by feketemihai** [comment]
> > Hi, probably yes, i think it can be added, but this was not my scope, so i suggest to merge this one like this, and after we can check in separate PR's.
> 
> Hi @feketemihai , do you think you'll have some time to add this feature?

Hi @francesco-ooops, like i said it was out of the scope, probably in september we can add it, if no one else is more quicker.

**Comment by francesco-ooops** [comment]
> > > Hi, probably yes, i think it can be added, but this was not my scope, so i suggest to merge this one like this, and after we can check in separate PR's.
> > 
> > 
> > Hi @feketemihai , do you think you'll have some time to add this feature?
> 
> Hi @francesco-ooops, like i said it was out of the scope, probably in september we can add it, if no one else is more quicker.

Thanks a lot, that's the info I needed :)

**Pull request merged**
