### PR TITLE
[14.0][FIX] sale_order_invoice_date: Correct POS Incompatibility

### PR DESCRIPTION
**Pull request by majouda**
This PR is for the issue number #242

### CODE REVIEW

**Comment by majouda** [comment]
Hello @ivantodorovich 
I don't know why the pre-commit check doesn't pass. 
Can you please review this PR? 

Thank you.

**Review by ivantodorovich — APPROVED** [review]
LGTM

As for the pre-commit issue, indeed it seems unrelated to this PR.
Perhaps an update from the repo template solves it.
Could you try with `copier -f update` ?

**Comment by majouda** [comment]
> LGTM
> 
> As for the pre-commit issue, indeed it seems unrelated to this PR. Perhaps an update from the repo template solves it. Could you try with `copier -f update` ?

Hello @ivantodorovich 
I tried to apply `copier -f update` but it adds a lot of changes
I revert the 'Updated from template' commit. 
Can you please try from your side to update the repository? 

Thank you in advance.

**Comment by ivantodorovich** [comment]
Hello @majouda 

I've just created this PR to update the dotfiles from the copier template:
- https://github.com/OCA/sale-reporting/pull/256

Let's wait until it's approved & merged, and you can rebase your PR afterwards

**Comment by ivantodorovich** [comment]
You can rebase now

**Comment by majouda** [comment]
> You can rebase now

@ivantodorovich Rebase done. Thank you for your support.

**Comment by ivantodorovich** [comment]
Thanks for fixing this ❤️ 

/ocabot merge patch

**Comment by majouda** [comment]
> Thanks for fixing this ❤️
> 
> /ocabot merge patch

with pleasure, Thank you @ivantodorovich

**Pull request merged**
