### PR TITLE
[16.0][MIG] sale_order_product_recommendation_product_sold_by_delivery_week: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@tecnativa TT42433

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
@sergio-teruel , @chienandalu  and @pedrobaeza  please review test requirements.txt if I am missing something

**Comment by pedrobaeza** [comment]
/ocabot migration sale_order_product_recommendation_product_sold_by_delivery_week

**Comment by sergio-teruel** [comment]
@Yadier-Tecnativa sale_order_product_recommendation already merged, so remove the requirement commit.
Thanks

**Comment by sergio-teruel** [comment]
ping @juangomezzurita

**Comment by Yadier-Tecnativa** [comment]
Done, pass all check except the runboat

**Comment by pilarvargas-tecnativa** [comment]
Check if the wizard layout looks correct.

image

**Comment by Yadier-Tecnativa** [comment]
> Check if the wizard layout looks correct.
@pilarvargas-tecnativa  If you tried it locally, you should update the sale-workflow repo, since this problem comes from the view (sale_order_recommendation_view_form) and is corrected in the sale_order_product_recommendation module.
Already the PR of sale_order_product_recommendation: Migration to version 16.0
#2491 merged and from this one, which is dependent, the push was given again.

**Comment by pilarvargas-tecnativa** [comment]
> Check if the wizard layout looks correct.
> @pilarvargas-tecnativa If you tried it locally, you should update the sale-workflow repo, since this problem comes from the view (sale_order_recommendation_view_form) and is corrected in the sale_order_product_recommendation module.
> Already the PR of sale_order_product_recommendation: Migration to version 16.0
> #2491 merged and from this one, which is dependent, the push was given again.

No, I did the test on the runboat of this PR, maybe it needs a rebase?

**Comment by Yadier-Tecnativa** [comment]
Done, (re-push)

**Review by pilarvargas-tecnativa — APPROVED** [review]
LGTM :)

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
