### PR TITLE
[10.0][IMP] sale_comment_template: add comments on sale order lines

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Adds the "sale order line formatted comments" feature of https://github.com/OCA/sale-reporting/pull/51.

### CODE REVIEW

**Review by bodedra — COMMENTED** [review]
@mreficent If you create invoice from sale order either "Down payment (percentage)" or "Down payment (fixed amount)" option. Text are not copied to invoice.

**Comment by MiquelRForgeFlow** [comment]
@bodedra That's not my problem. This PR is just adding a feature, not fixing other things. But if you or others provide correct fixes, then I can include them.

**Comment by bodedra** [comment]
@mreficent then how about change documentation information ?

**Comment by MiquelRForgeFlow** [comment]
I just changed the documentation to add the new feature. I am not touching other things.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test :+1: 

LGTM

obama

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza

**Review by bodedra — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
This is not just an improvement. It is a fix. It makes this module compatible with https://github.com/OCA/sale-workflow/tree/10.0/sale_order_line_sequence and other modules that inherit the standard sale report.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
