### PR TITLE
[ADD] sale_packaging_report: packaging data in sale reports

### PR DESCRIPTION
**Pull request by yajo**
This module displays packaging data (quantity and type) in:

Sale order printed reports:
flameshot_2023-09-07_11-47_1

Sale BI reports:
flameshot_2023-09-07_11-47

@moduon MT-3773

### CODE REVIEW

**Review by rafaelbn — COMMENTED** [review]
Tested 👍🏼 

For me a small UX/Understangind change. I could ask for more opinions.

"Packaging name: packing_qty"

Actually is:

"(packing_qty Packaging name)"

So I see better:

- Caja 12: 1.0
- Pieza: 1.0
- Caja 2 Paletas: 1.0

imagen


Around report I see this: real sale qty is delivered so could add in the report a second computed measure?

imagen

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @yajo 

image

**Comment by fcvalgar** [comment]
> Tested 👍🏼
> 
> For me a small UX/Understangind change. I could ask for more opinions.
> 
> "Packaging name: packing_qty"
> 
> Actually is:
> 
> "(packing_qty Packaging name)"
> 
> So I see better:
> 
> * Caja 12: 1.0
> * Pieza: 1.0
> * Caja 2 Paletas: 1.0
> 
> imagen
> 
> Around report I see this: real sale qty is delivered so could add in the report a second computed measure?
> 
> imagen

I think the same about printing the sale order.

Packaging name: packing_qty or any other separator is better.

**Review by Shide — APPROVED** [review]
Code lgtm

**Comment by yajo** [comment]
> "Packaging name: packing_qty"

Done.



> could add in the report a second computed measure?

Done.

**Comment by yajo** [comment]
@sbidoul any clues on how to fix https://github.com/OCA/sale-reporting/pull/231#issuecomment-1713267278?

**Comment by sbidoul** [comment]
@yajo this looks like a rst syntax error at line 73 of README.rst. Perhaps put line 72 and 73 on a single line?

**Pull request merged**
