### PR TITLE
[FIX] [16.0] sale_report_delivered: Decide when SUM valuation layers or sub lines

### PR DESCRIPTION
**Pull request by Shide**
When the valuation layers were being grouped, the COALESCE function was acting on each one separately. Now, they are all processed at once. If there is a valuation layer, it is used; if not, data is taken from the subquery.

MT-6706 @moduon @yajo @rafaelbn @fcvalgar @gelojr please review if you want ;)

### CODE REVIEW

**Review by Gelojr — APPROVED** [review]
LGTM https://www.loom.com/share/36f9d9fac79b4a2c98e74f7ff5ed5adf?sid=b408f6aa-4115-4f71-a4c4-1a2be09fef78

**Review by yajo — APPROVED** [review]

**Review by fcvalgar — APPROVED** [review]
Functional review.
LGTM, thank you @Shide 

image

image

image

**Comment by Shide** [comment]
wait to test in a staging database until merged. it's a corner case

**Comment by Shide** [comment]
Fixed missing COALESCE when sum valuation layers on margin.

**Comment by Shide** [comment]
@sergio-teruel this PR has been tested on local and staging (customer) environments and works fine.

Can you merge please?

**Pull request merged**
