### PR TITLE
[ADD] sale_report_country_state: New module

### PR DESCRIPTION
**Pull request by chienandalu**
This module allows to filter by partner's state in the sale reports.

cc @Tecnativa TT22029

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Functional review in local :+1:

**Comment by pedrobaeza** [comment]
Travis is red, and I personally don't like too much the name, as it's misleading. Starting with, the field is added more for grouping than for filtering. And `state` word is used also for reflecting an object status. What about calling it `sale_report_country_state`?

**Comment by chienandalu** [comment]
Ok, with the name. The travis error is a little bit weird. No test related, although the branch seems to be green

**Comment by pedrobaeza** [comment]
Travis fixed in https://github.com/OCA/sale-reporting/commit/7d177148e50bf25771efe89a33f4e0a1dfdc4fe1

Please rename and rebase.

**Comment by chienandalu** [comment]
@pedrobaeza Module name changed :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
