### PR TITLE
[16.0][mig] base_multicompany_reporting_currency: Migration to 16.0

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by peluko00** [comment]
Needs review

**Comment by peluko00** [comment]
@pedrobaeza Seems runboat doesn't work. How can I fix this?
I need this module because depends in crm_multicompany_reporting_currency in this[ pr ](https://github.com/OCA/crm/pull/508)

**Comment by pedrobaeza** [comment]
Push again for triggering a new build. Last week it was not working. You can git amend and push -f for example.

**Comment by peluko00** [comment]
> Push again for triggering a new build. Last week it was not working. You can git amend and push -f for example.

@dsolanki-initos Can you push again please

**Pull request closed without merging**
