### PR TITLE
[16.0][MIG] product_sold_by_delivery_week: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT42422

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
@sergio-teruel and @pedrobaeza 

the job fail:  Starting job container
  /usr/bin/docker --config /home/runner/work/_temp/.docker_527be9d3-bb8a-48bd-bd4b-c6c345bc14cb login ghcr.io -u Yadier-Tecnativa --password-stdin
  Error: Docker login for 'ghcr.io' failed with exit code 1
  
 maybe run the job again?

**Comment by pedrobaeza** [comment]
Yes, it seems a glitch

**Comment by Yadier-Tecnativa** [comment]
passed

**Review by chienandalu — APPROVED** [review]
Tested

ping @sergio-teruel

**Review by sergio-teruel — APPROVED** [review]
Functional review OK

**Comment by sergio-teruel** [comment]
ping @juangomezzurita

**Pull request merged**
