### PR TITLE
Replace 'Camptocamp SA' with 'Camptocamp'

### PR DESCRIPTION
**Pull request by vvrossem**
This pull request contains changes to replace 'Camptocamp SA' with 'Camptocamp' in __manifest__.py files for branch 15.0.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why are you ignoring me about the commit message?

**Review by yankinmax — APPROVED** [review]

**Comment by vvrossem** [comment]
I am not ignoring you. I'm currently fixing

**Comment by pedrobaeza** [comment]
Well, you put about 30 PRs with the same structure after my repeated messages, collapsing all yesterday and part of today with the pipelines. And now another round of pipelines with the changes. That's a waste of resources and not very ecological and responsible.

**Comment by vvrossem** [comment]
You are completely right. I didn't read your messages until this morning. 
My apologies for not ensuring the commit message was respected and for wasting resources.

**Pull request closed without merging**
