### PR TITLE
[17.0][MIG] sale_comment_template: Migration to 17.0

### PR DESCRIPTION
**Pull request by RogerSans**
Supersede: https://github.com/OCA/sale-reporting/pull/265
Standard migration
T-6460

@HaraldPanten 
@ValentinVinagre 
@luis-ron

### CODE REVIEW

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Comment by RogerSans** [comment]
@manuelregidor Can you review this pls?

**Review by manuelregidor — APPROVED** [review]
Technical review. LGTM

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
