### PR TITLE
[IMP]sale_comment_template: render html in report

### PR DESCRIPTION
**Pull request by odooNextev**
#246

### CODE REVIEW

**Comment by odooNextev** [comment]
@pedrobaeza small fix but important.
What do you opinion? Thanks

**Comment by pedrobaeza** [comment]
`t-raw` is deprecated. You should consider using `Markup` instead, but this fix is not correct.

**Comment by odooNextev** [comment]
Thanks @pedrobaeza, I will open a new pr on reporting-engine to add this improvement to base_comment_template

**Comment by odooNextev** [comment]
This is the pr to fix it https://github.com/OCA/reporting-engine/pull/833

**Pull request closed without merging**
