### PR TITLE
[14.0][MIG] sale comment template

### PR DESCRIPTION
**Pull request by petrus-v**
This PR depends on that one [account_comment_template migration PR](https://github.com/OCA/account-invoice-reporting/pull/165)

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
👍 Tested in my local

**Review by SimoneVagile — APPROVED** [review]

**Review by stevech091 — APPROVED** [review]
Functional test OK

**Comment by SimoRubi** [comment]
https://github.com/OCA/account-invoice-reporting/pull/165 has been merged, can you trigger a restart of CI jobs?

**Comment by petrus-v** [comment]
> [OCA/account-invoice-reporting#165](https://github.com/OCA/account-invoice-reporting/pull/165) has been merged, can you trigger a restart of CI jobs?

I've manually [triggered a rebuild](https://travis-ci.com/github/OCA/sale-reporting/jobs/475638278), wait for it...

**Comment by petrus-v** [comment]
> > [OCA/account-invoice-reporting#165](https://github.com/OCA/account-invoice-reporting/pull/165) has been merged, can you trigger a restart of CI jobs?
> 
> I've manually [triggered a rebuild](https://travis-ci.com/github/OCA/sale-reporting/jobs/475638278), wait for it...

PR is green :rocket: :fireworks:

**Comment by SimoRubi** [comment]
@OCA/crm-sales-marketing-maintainers can this be merged?

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
