### PR TITLE
[14.0][MIG] sale_order_weight

### PR DESCRIPTION
**Pull request by SimoRubi**
Migration from https://github.com/OCA/sale-workflow/tree/687b44f6410cf486955dc7039202891aaf6ba826/sale_order_weight.

The module has changed repository because of https://github.com/OCA/sale-workflow/pull/459#issuecomment-298919868.

### CODE REVIEW

**Review by tafaRU — CHANGES_REQUESTED** [review]
Please remove all po files but 'it.po` as they are not synced.
The rest LGTM, thanks!

**Comment by SimoRubi** [comment]
> Please remove all po files but 'it.po` as they are not synced.
> The rest LGTM, thanks!

Thanks for the review!
I haven't found any hint on removing translations in the OCA migration guidelines https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

I'd rather let the translations be in the migrated module, because I see removing them as a loss of the translated data; unless they might cause some issue.

What issues can they cause?

**Review by tafaRU — APPROVED** [review]
Just read https://discord.com/channels/753902328494424064/822435512391303209/862609757953196052 so :+1:

**Comment by NL66278** [comment]
@tafaRU What is the discord channel you are referring to? Anyway I do not have access, even though logged in with my discord account. Better copy something you want to say to here...

**Comment by tafaRU** [comment]
Hi @NL66278, I'm referring to one of `Odoo Italia` channel where we discussed about removing old po files during a module migration. And at the end, it was agreed that it's better to keep them to avoid losing existing translations.

**Comment by SimoRubi** [comment]
@OCA/crm-sales-marketing-maintainers can this be merged or do I need to fix anything?
Thanks!

**Pull request merged**
