### PR TITLE
[FIX] lp bug 1315445

### PR DESCRIPTION
**Pull request by eLBati**
ported from
https://code.launchpad.net/~agilebg/sale-reports/7_fix_1315445/+merge/223795

### CODE REVIEW

**Comment by bwrsandman** [comment]
@eLBati since you authored this, do you mind explaining the changes made here and what the original problem was.

**Comment by eLBati** [comment]
This should fix the bug described here
https://bugs.launchpad.net/sale-reports/+bug/1315445

More info at https://bugs.launchpad.net/account-invoice-report/+bug/1277024

The current status of the work is summarized by my last comment at https://code.launchpad.net/~agilebg/account-invoice-report/7.0-fix_invoice_webkit_description_bugs/+merge/205204/comments/536315 that applies to the 3 modules, invoice_webkit, sale_order_webkit and purchase_order_webkit

The only difference is that purchase_order_webkit does not have the 'formatted notes', so it does not suffer from [bug 1231329](https://bugs.launchpad.net/account-invoice-report/+bug/1231329)

**Comment by eLBati** [comment]
Same as https://github.com/OCA/account-invoice-reporting/pull/2

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
