### PR TITLE
[17.0][MIG] sale_layout_category_hide_detail: Migration to 17.0

### PR DESCRIPTION
**Pull request by jeroenev**

### CODE REVIEW

**Review by navarrorico — CHANGES_REQUESTED** [review]
Tested on runboat. The icon buttons of the section are not working.

**Comment by jeroenev** [comment]
Did you test on a Quote or confirmed SO? buttons are only clickable when the quote is not yet confirmed.
This was the same in Odoo16, but I know this was not the case in Odoo14, which might cause some confusion if you know the module from an older Odoo version.
Work correctly on this quote: http://oca-sale-reporting-17-0-pr253-e9ff0b161700.runboat.odoo-community.org/web#id=3&cids=1&menu_id=183&action=313&model=sale.order&view_type=form

**Review by navarrorico — APPROVED** [review]
@jeroenev True!!! Sorry. All wroks fine then. Thank you

Functional review LGTM :+1:

**Comment by willievmobile** [comment]
@jeroenev ive really tried for weeks i cannot get this to work on a odoo17 thats been updated to the version starting this month..?
Im desperately needing this to work for the company so we can use odoo17 as without this we have to make 2 quotes for every job. please help?

**Comment by Ricardoalso** [comment]
> @jeroenev ive really tried for weeks i cannot get this to work on a odoo17 thats been updated to the version starting this month..? Im desperately needing this to work for the company so we can use odoo17 as without this we have to make 2 quotes for every job. please help?

Hello @willievmobile, can you give me more context please ?

**Comment by willievmobile** [comment]
@jeroenev I gave up on this issue and just installed odoo 16 and we are working on that.
But basically it looked like it was how the server from Cloudclusters was installed or something. but i just dont know enough to figure it out.

**Comment by trisdoan** [comment]
> @jeroenev I gave up on this issue and just installed odoo 16 and we are working on that. But basically it looked like it was how the server from Cloudclusters was installed or something. but i just dont know enough to figure it out.

Hello @willievmobile, I guess the issue you encountered is **500 Internal Server Error**

If yes, I prepared an PR to fix it in  https://github.com/jeroenev/sale-reporting/pull/1. Hello @jeroenev, could you plz take this fix into account?

**Review by leemannd — APPROVED** [review]

**Comment by jeroenev** [comment]
@trisdoan any instructions how I would integrate that PR into mine? Not too well versed in the OCA workflows for that

**Comment by trisdoan** [comment]
Hello @jeroenev, you can go to my PR and merge like this

sample

**Comment by jeroenev** [comment]
OK that was easier than expected, thanks a lot!

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/sale-reporting/pull/276 to commit history (before migration commit)

**Comment by arianzaghi** [comment]
@jeroenev Hi! How long is left before the merge?

**Comment by yvaucher** [comment]
As the PR is ready, we can tackle the FW port of #276 in a later PR.

**Pull request merged**
