### PR TITLE
[14.0][ADD] sale_outgoing_product: Add new module to show products to be delivered in sales

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've added the module sale_outgoing_products, this module allow to see the products to be sent in sales module

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by petrus-v — APPROVED** [review]
Reading code only looks good to me :+1: thanks

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Comment by pedrobaeza** [comment]
Please don't use plurals in module names.

**Comment by alan196** [comment]
@pedrobaeza the module was renamed to sale_outgoing_product could you help me to merge this PR 🙏

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
