### PR TITLE
[IMP] sale_order_product_recommendation_product_sold_by_delivery_week: display qty on hand

### PR DESCRIPTION
**Pull request by yajo**
If you care about last delivered items, you probably care about how many items you have on hand.

This improvement displays that info.

@moduon MT-4472

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Tested 👍🏼 

https://www.loom.com/share/e25a52dce89745498f5227f8f833ba7c?sid=0aa91843-ffa9-48e0-80dc-8d8970bd5e99

Just one nice to  have @yajo , could we change label from Quantity yo Qty?

imagen

**Review by EmilioPascual — APPROVED** [review]
LGTM

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @yajo

**Comment by Shide** [comment]
**praise:** Cool feature, this info is always welcome

**suggestion:** Is it possible to display the same widget? Gives more information, small width and same appearance.

If it's not possible, it's perfect for me

**Review by Shide — APPROVED** [review]

**Comment by yajo** [comment]
> **suggestion:** Is it possible to display the same widget? Gives more information, small width and same appearance.

It seems tightly coupled with the `sale.order.line` model. I added this to the roadmap, and we can leave the current version as a MVP.

**Comment by yajo** [comment]
> could we change label from Quantity yo Qty?

Changed.

**Comment by yajo** [comment]
@sergio-teruel @chienandalu any comments on this one?

**Review by chienandalu — APPROVED** [review]
LGTM Thanks :) :+1:

**Comment by yajo** [comment]
I just pushed the roadmap change said in https://github.com/OCA/sale-reporting/pull/244#issuecomment-1857549346 that I forgot to commit.

/ocabot merge minor

**Pull request merged**
