### PR TITLE
[MIG] sale_reporting_weight: Migration to 11.0

### PR DESCRIPTION
**Pull request by chienandalu**
This module adds another possible source to the sales report weight value:

* If the UoM of the product is one of the category "Weight", the value is taken
  from the ordered quantity.

cc @Tecnativa

### CODE REVIEW

**Comment by chienandalu** [comment]
Closing as the value is now available in the standard

**Comment by pedrobaeza** [comment]
But we nee the tweak...

**Comment by chienandalu** [comment]
Yes, sorry. Can you reopen it?

**Comment by pedrobaeza** [comment]
It seems you have deleted the branch, so until you upload again the branch it's not possible.

**Comment by chienandalu** [comment]
It's still there: https://github.com/Tecnativa/sale-reporting/tree/11.0-mig-sale_reporting_weight

**Comment by pedrobaeza** [comment]
Well, there's something weird, as I can reopen it. Just create other PR.

**Comment by chienandalu** [comment]
Ok, sorry for the inconvenience :confused:

**Comment by chienandalu** [comment]
Superseeded by: https://github.com/OCA/sale-reporting/pull/59

**Pull request closed without merging**
