### PR TITLE
[MIG] sale_report_delivered_subtotal: Migration to 14.0

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT38067

please review @CarlosRoca13 @LudLaf

### CODE REVIEW

**Review by LudLaf — APPROVED** [review]
Functionality is working fine.

**Review by LudLaf — CHANGES_REQUESTED** [review]
Name of these two terms (*Sales Report* and *Sales Analysis*) should be unified


.

**Comment by chienandalu** [comment]
Fixed

**Review by LudLaf — APPROVED** [review]
LGTM

**Comment by chienandalu** [comment]
ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]
LGTM

**Pull request merged**
