### PR TITLE
[15.0][MIG] sale_order_line_position

### PR DESCRIPTION
**Pull request by ajaniszewska-dev**

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
LG but please rewrite your commits to include the module name

**Review by sebalix — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
Sorry, just noticed the 1st commit before the mig is kind of useless by itself, it should be squashed on top of the migration one.
Not a blocker tho.

**Pull request merged**
