### PR TITLE
[11.0][MIG] sale_proforma_report

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Migration to v11.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
v11 already has this as a native feature, so no need of migrating this. You only need to check the corresponding setting.

**Comment by LoisRForgeFlow** [comment]
Ups, didn't know. Thanks for pointing it!!

**Comment by pedrobaeza** [comment]
It's good to look at the migration issue where it was noted that already. What you can do is to include the OpenUpgrade merge mechanism, and look for a way to auto-add the group to all if you had previously installed that module (maybe checking the existence of an XML-ID).

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza started the work here: https://github.com/OCA/OpenUpgrade/pull/1572

**Pull request closed without merging**
