### PR TITLE
[MIG] Migrate sale_order_weight and moving to sale_reporting

### PR DESCRIPTION
**Pull request by hurrinico**
Based on https://github.com/OCA/sale-workflow/pull/459

### CODE REVIEW

**Comment by eLBati** [comment]
@hurrinico so the commits from sale-workflow/9.0 can't be retrieved?

**Comment by hurrinico** [comment]
@eLBati the module didn't go on version 9

**Comment by eLBati** [comment]
@hurrinico from sale-workflow/8.0 ?

**Comment by hurrinico** [comment]
@eLBati  i've tried but i can't do it

**Comment by eLBati** [comment]
On 31 May 2017 at 16:12, hurrinico <notifications@github.com> wrote:

> @eLBati <https://github.com/elbati> i've tried but i can't do it
>
>
>
Do you get conflicts or other errors?

**Comment by hurrinico** [comment]
@eLBati no error or conflict, but following the steps that @pedrobaeza told me in the other pr i can't retrieve the commit

**Comment by pedrobaeza** [comment]
I'm afraid you haven't followed the steps, or there will be more commits.

**Comment by yajo** [comment]
The steps are here, just in case: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Pull request closed without merging**
