### PR TITLE
[12.0][FIX] sale_layout_category_hide_detail: Incompleted js file

### PR DESCRIPTION
**Pull request by Danoolo**
After migration to 12.0 this module made an error: 

Uncaught TypeError: Cannot read property 'options' of undefined
at Class.renderHeaderCell (web.assets_backend.js:3517)
at Class.renderHeaderCell (web.assets_common.js:3541)
at Function..map..collect (web.assets_common.js:13)
at Class._renderHeader (web.assets_backend.js:1963)
at Class._renderView (web.assets_backend.js:1973)
at Class.prototype.(anonymous function) (http://localhost:8069/web/content/6439-ac471f7/web.assets_common.js:3538:488)
at Class._renderView (web.assets_backend.js:1915)
at Class. (web.assets_common.js:3541)
at Class._renderView (web.assets_backend.js:3295)
at Class._renderView (web.assets_common.js:3541)

This error came from sale_layout_category_hide_detail and check into this i got that the js file sale_layout_category_hide_detail.js is incompleted for me

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's an error in the PR because it contains changes for too much things.

**Comment by pedrobaeza** [comment]
File permissions have been changed

**Comment by Danoolo** [comment]
Sorry for wrong chmod changes...

**Comment by ernestotejeda** [comment]
I test on the runbot and I couldn't see the icons in the sections

**Comment by Danoolo** [comment]
Sorry...problem came from an own module that added a button in view tree for sale.order.line in sale.order view form but doesnt have options attribute...excuse me for disturb you..

**Comment by Tardo** [comment]
OTOH The implementation of the module is a bit confuse... Some comment here would be really appreciated:
https://github.com/OCA/sale-reporting/pull/80/files#diff-cbaa94569b634ce4dddaf5046e33d97cL60

Why not override 'SectionAndNoteListRenderer' directly?

**Comment by Danoolo** [comment]
Yep...i think it's a good option to directly modify...my error came from a button inserted in tree view (so, no field is associated)...then options variable in fieldsInfo list doesnt exist.

**Comment by ernestotejeda** [comment]
@Tardo In v12 and previous, SectionAndNoteListRenderer is not returned inside the scope it was defined so i can't be override directly but fortunately in Odoo 13.0 yes (https://github.com/odoo/odoo/blob/633b931d4565b7e81ef69f6554a0a69b002b78e3/addons/account/static/src/js/section_and_note_fields_backend.js#L105) . The v13 migration of this module that is doing @sebalix (https://github.com/OCA/sale-reporting/pull/76) that improvement is taken into account.

**Pull request closed without merging**
