### PR TITLE
[16.0][IMP] sale_comment_template: allow to use dynamic information in template

### PR DESCRIPTION
**Pull request by alan196**
With this change, it allows to define dynamic information from the sale order in the template

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
- `t-raw` is deprecated. Use `t-out`. Anyway, that's not for dynamic expressions, but for HTML.
- This is not `[ADD]`, but `[IMP]`.

**Comment by alan196** [comment]
@pedrobaeza thanks for the review 👍 

I have updated the requested changes

**Review by pedrobaeza — APPROVED** [review]

**Comment by alan196** [comment]
@pedrobaeza I just updated the PR to use qweb rendering instead of inline rendering engine, or do you think is better to make a PR to base_comment_template module in order to make qweb rendering the default?

**Comment by pedrobaeza** [comment]
I think that the syntax should be defined at template level.

**Review by YahairaCVJarsa — APPROVED** [review]

**Pull request merged**
